2019-05-20 07:31:41.102 [error] <0.234.0> gen_server 'Elixir.RabbitBroadway.Producer_default_2' terminated with reason: {{shutdown,{server_initiated_close,404,<<"NOT_FOUND - no queue 'my_queue' in vhost '/'">>}},{gen_server,call,[<0.342.0>,{subscribe,{'basic.consume',0,<<"my_queue">>,<<>>,false,false,false,false,[]},<0.347.0>},60000]}} in gen_server:call/3 line 223
2019-05-20 08:54:13.419 [error] <0.265.0> gen_server <0.265.0> terminated with reason: bad return value: {noreply,#{},#{}}
2019-05-20 09:03:49.873 [error] <0.265.0> gen_server <0.265.0> terminated with reason: bad return value: {noreply,#{},#{}}
2019-05-20 09:18:59.594 [error] <0.256.0> gen_server <0.256.0> terminated with reason: bad return value: {noreply,#{},#{}}
2019-05-20 09:18:59.615 [error] <0.256.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.256.0> with 3 neighbours exited with reason: bad return value: {noreply,#{},#{}} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:27:07.376 [error] <0.255.0> gen_server <0.255.0> terminated with reason: bad return value: {noreply,#{},#{}}
2019-05-20 09:27:07.386 [error] <0.255.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.255.0> with 3 neighbours exited with reason: bad return value: {noreply,#{},#{}} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:28:51.154 [error] <0.264.0> gen_server <0.264.0> terminated with reason: bad return value: {noreply,1000,#{}}
2019-05-20 09:28:51.163 [error] <0.264.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.264.0> with 3 neighbours exited with reason: bad return value: {noreply,1000,#{}} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:30:16.941 [error] <0.256.0> gen_server <0.256.0> terminated with reason: bad return value: {noreply,1000,#{}}
2019-05-20 09:30:16.950 [error] <0.256.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.256.0> with 3 neighbours exited with reason: bad return value: {noreply,1000,#{}} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:31:48.244 [error] <0.264.0> gen_server <0.264.0> terminated with reason: {badkey,events,#{}} in 'Elixir.Imageresizer':handle_demand/2 line 25
2019-05-20 09:31:48.265 [error] <0.264.0> CRASH REPORT Process <0.264.0> with 3 neighbours crashed with reason: {badkey,events,#{}} in 'Elixir.Imageresizer':handle_demand/2 line 25
2019-05-20 09:36:53.617 [error] <0.266.0> gen_server <0.266.0> terminated with reason: bad return value: {noreply,#{},dummy}
2019-05-20 09:36:53.626 [error] <0.266.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.266.0> with 3 neighbours exited with reason: bad return value: {noreply,#{},dummy} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:37:46.535 [error] <0.267.0> GenStage consumer <0.267.0> cannot dispatch events (an empty list must be returned): [1,2,3]
2019-05-20 09:39:03.982 [error] <0.258.0> gen_server <0.258.0> terminated with reason: bad return value: {noreply,ok}
2019-05-20 09:39:03.991 [error] <0.258.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.258.0> with 3 neighbours exited with reason: bad return value: {noreply,ok} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:40:05.774 [error] <0.267.0> gen_server <0.267.0> terminated with reason: bad return value: {noreply,ok,dummy}
2019-05-20 09:40:05.782 [error] <0.267.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.267.0> with 3 neighbours exited with reason: bad return value: {noreply,ok,dummy} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:40:37.044 [error] <0.267.0> gen_server <0.267.0> terminated with reason: bad return value: {noreply,0,dummy}
2019-05-20 09:40:37.053 [error] <0.267.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.267.0> with 3 neighbours exited with reason: bad return value: {noreply,0,dummy} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:40:55.079 [error] <0.266.0> gen_server <0.266.0> terminated with reason: bad return value: {noreply,0,0}
2019-05-20 09:40:55.089 [error] <0.266.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.266.0> with 3 neighbours exited with reason: bad return value: {noreply,0,0} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:46:54.940 [error] <0.265.0> gen_server <0.265.0> terminated with reason: bad return value: {noreply,#{},#{}}
2019-05-20 09:46:54.950 [error] <0.265.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.265.0> with 3 neighbours exited with reason: bad return value: {noreply,#{},#{}} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:47:20.350 [error] <0.255.0> gen_server <0.255.0> terminated with reason: bad return value: {noreply,#{},3}
2019-05-20 09:47:20.363 [error] <0.255.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.255.0> with 3 neighbours exited with reason: bad return value: {noreply,#{},3} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:48:14.039 [error] <0.264.0> gen_server <0.264.0> terminated with reason: bad return value: {noreply,#{name => <<"filename">>},#{name => <<"filename">>}}
2019-05-20 09:48:14.050 [error] <0.264.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.264.0> with 3 neighbours exited with reason: bad return value: {noreply,#{name => <<"filename">>},#{name => <<"filename">>}} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:49:41.578 [error] <0.264.0> gen_server <0.264.0> terminated with reason: bad return value: {noreply,#{name => <<"filename">>}}
2019-05-20 09:49:41.587 [error] <0.264.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.264.0> with 3 neighbours exited with reason: bad return value: {noreply,#{name => <<"filename">>}} in gen_server:handle_common_reply/8 line 751
2019-05-20 09:57:42.078 [error] <0.266.0>@Elixir.GenStage:noreply_callback:2053 gen_server <0.266.0> terminated with reason: call to undefined function 'Elixir.Imagewatermark':handle_cast/2 from 'Elixir.GenStage':noreply_callback/3 line 2053
2019-05-20 09:57:42.092 [error] <0.266.0>@Elixir.Imagewatermark:handle_cast CRASH REPORT Process <0.266.0> with 3 neighbours crashed with reason: call to undefined function 'Elixir.Imagewatermark':handle_cast({processimage,#{}}, #{})
2019-05-20 09:58:34.889 [error] <0.265.0> gen_server <0.265.0> terminated with reason: bad return value: {noreply,#{},#{}}
2019-05-20 09:58:34.898 [error] <0.265.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.265.0> with 3 neighbours exited with reason: bad return value: {noreply,#{},#{}} in gen_server:handle_common_reply/8 line 751
2019-05-20 10:00:13.878 [error] <0.256.0> gen_server <0.256.0> terminated with reason: bad return value: {noreply,#{from => <<"direct">>,name => <<"filename">>},#{}}
2019-05-20 10:00:13.886 [error] <0.256.0>@gen_server:handle_common_reply:751 CRASH REPORT Process <0.256.0> with 3 neighbours exited with reason: bad return value: {noreply,#{from => <<"direct">>,name => <<"filename">>},#{}} in gen_server:handle_common_reply/8 line 751
2019-05-20 10:23:32.019 [error] <0.354.0>@gen_server:init_it:366 CRASH REPORT Process <0.354.0> with 1 neighbours exited with reason: bad return value: nil in gen_server:init_it/6 line 366
2019-05-20 11:28:01.399 [error] <0.354.0>@gen_server:init_it:358 CRASH REPORT Process <0.354.0> with 2 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 358
2019-05-20 11:28:42.063 [error] <0.354.0>@gen_server:init_it:358 CRASH REPORT Process <0.354.0> with 2 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 358
2019-05-20 11:46:44.003 [error] <0.356.0>@gen_server:init_it:358 CRASH REPORT Process <0.356.0> with 2 neighbours exited with reason: no such process or port in call to gen_server:init_it/6 line 358
2019-05-21 10:30:31.108 [error] <0.306.0>@Elixir.Imageresizer:handle_call:20 gen_server 'Elixir.Imageresizer' terminated with reason: bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20
2019-05-21 10:30:31.116 [error] <0.306.0>@Elixir.Imageresizer:handle_call:20 CRASH REPORT Process 'Elixir.Imageresizer' with 0 neighbours crashed with reason: bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20
2019-05-21 10:30:31.116 [error] <0.238.0>@Elixir.Imageresizer:handle_call:20 Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imageresizer' started with 'Elixir.Imageresizer':start_link([]) at <0.306.0> exit with reason bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20 in context child_terminated
2019-05-21 10:30:31.117 [error] <0.307.0>@Elixir.Imageresizer:handle_call:20 gen_server 'Elixir.Imagewatermark' terminated with reason: bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20
2019-05-21 10:30:31.119 [error] <0.307.0>@Elixir.Imageresizer:handle_call:20 CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours exited with reason: bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20
2019-05-21 10:30:31.119 [error] <0.238.0>@Elixir.Imageresizer:handle_call:20 Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.307.0> exit with reason bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20 in context child_terminated
2019-05-21 10:30:31.119 [error] <0.308.0>@Elixir.Imageresizer:handle_call:20 gen_server 'Elixir.Exporter' terminated with reason: bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20
2019-05-21 10:30:31.120 [error] <0.308.0>@Elixir.Imageresizer:handle_call:20 CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20
2019-05-21 10:30:31.120 [error] <0.238.0>@Elixir.Imageresizer:handle_call:20 Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.308.0> exit with reason bad argument in call to erlang:apply(<<"warthog.jpg, S3R556, jpg">>, id, []) in 'Elixir.Imageresizer':handle_call/3 line 20 in context child_terminated
2019-05-21 16:37:51.002 [error] <0.312.0> CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours crashed with reason: {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24
2019-05-21 16:37:51.002 [error] <0.243.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.312.0> exit with reason {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24 in context child_terminated
2019-05-21 16:37:51.003 [error] <0.313.0> gen_server 'Elixir.Exporter' terminated with reason: {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24
2019-05-21 16:37:51.004 [error] <0.313.0> CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24 in gen_server:handle_common_reply/8 line 751
2019-05-21 16:37:51.004 [error] <0.243.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.313.0> exit with reason {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24 in context child_terminated
2019-05-21 16:41:41.138 [error] <0.307.0> gen_server 'Elixir.Imagewatermark' terminated with reason: {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24
2019-05-21 16:41:41.145 [error] <0.307.0> CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours crashed with reason: {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24
2019-05-21 16:41:41.145 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.307.0> exit with reason {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24 in context child_terminated
2019-05-21 16:41:41.146 [error] <0.308.0> gen_server 'Elixir.Exporter' terminated with reason: {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24
2019-05-21 16:41:41.146 [error] <0.308.0> CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24 in gen_server:handle_common_reply/8 line 751
2019-05-21 16:41:41.147 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.308.0> exit with reason {badmap,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}]} in 'Elixir.Imagewatermark':handle_events/3 line 24 in context child_terminated
2019-05-21 16:42:34.012 [error] <0.307.0> gen_server 'Elixir.Imagewatermark' terminated with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]}
2019-05-21 16:42:34.016 [error] <0.307.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours exited with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-21 16:42:34.016 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.307.0> exit with reason bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]} in context child_terminated
2019-05-21 16:42:34.017 [error] <0.308.0> gen_server 'Elixir.Exporter' terminated with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]}
2019-05-21 16:42:34.017 [error] <0.308.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-21 16:42:34.017 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.308.0> exit with reason bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]} in context child_terminated
2019-05-21 16:44:15.027 [error] <0.307.0> gen_server 'Elixir.Imagewatermark' terminated with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]}
2019-05-21 16:44:15.030 [error] <0.307.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours exited with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-21 16:44:15.031 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.307.0> exit with reason bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]} in context child_terminated
2019-05-21 16:44:15.031 [error] <0.308.0> gen_server 'Elixir.Exporter' terminated with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]}
2019-05-21 16:44:15.031 [error] <0.308.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-21 16:44:15.031 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.308.0> exit with reason bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => error}],[]} in context child_terminated
2019-05-21 16:45:22.024 [error] <0.307.0> gen_server 'Elixir.Imagewatermark' terminated with reason: bad return value: {noreply,error,[],[]}
2019-05-21 16:45:22.028 [error] <0.307.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours exited with reason: bad return value: {noreply,error,[],[]} in gen_server:handle_common_reply/8 line 751
2019-05-21 16:45:22.028 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.307.0> exit with reason bad return value: {noreply,error,[],[]} in context child_terminated
2019-05-21 16:45:22.028 [error] <0.308.0> gen_server 'Elixir.Exporter' terminated with reason: bad return value: {noreply,error,[],[]}
2019-05-21 16:45:22.028 [error] <0.308.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: bad return value: {noreply,error,[],[]} in gen_server:handle_common_reply/8 line 751
2019-05-21 16:45:22.028 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.308.0> exit with reason bad return value: {noreply,error,[],[]} in context child_terminated
2019-05-21 16:45:56.036 [error] <0.298.0> gen_server 'Elixir.Imagewatermark' terminated with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}],[]}
2019-05-21 16:45:56.040 [error] <0.298.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours exited with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-21 16:45:56.040 [error] <0.229.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.298.0> exit with reason bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}],[]} in context child_terminated
2019-05-21 16:45:56.040 [error] <0.299.0> gen_server 'Elixir.Exporter' terminated with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}],[]}
2019-05-21 16:45:56.041 [error] <0.299.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-21 16:45:56.041 [error] <0.229.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.299.0> exit with reason bad return value: {noreply,error,[#{'__struct__' => 'Elixir.ImageProcessingModel',customer_id => <<"S3R556">>,destination_type => nil,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,path_from => nil,path_to => nil,status => ok}],[]} in context child_terminated
2019-05-22 08:19:56.311 [error] <0.298.0>@Elixir.Imageresizer:handle_call:29 gen_server 'Elixir.Imageresizer' terminated with reason: bad argument in call to erlang:apply([<<"FE51F,warthog.jpg,jpg">>], customer_id, []) in 'Elixir.Imageresizer':handle_call/3 line 29
2019-05-22 08:19:56.319 [error] <0.298.0>@Elixir.Imageresizer:handle_call:29 CRASH REPORT Process 'Elixir.Imageresizer' with 0 neighbours crashed with reason: bad argument in call to erlang:apply([<<"FE51F,warthog.jpg,jpg">>], customer_id, []) in 'Elixir.Imageresizer':handle_call/3 line 29
2019-05-22 08:20:41.086 [error] <0.299.0> gen_server 'Elixir.Imagewatermark' terminated with reason: {badkey,status,#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>}} in 'Elixir.Imagewatermark':handle_events/3 line 17
2019-05-22 08:20:41.099 [error] <0.299.0> CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours crashed with reason: {badkey,status,#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>}} in 'Elixir.Imagewatermark':handle_events/3 line 17
2019-05-22 08:20:41.099 [error] <0.229.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.299.0> exit with reason {badkey,status,#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>}} in 'Elixir.Imagewatermark':handle_events/3 line 17 in context child_terminated
2019-05-22 08:20:41.100 [error] <0.300.0> gen_server 'Elixir.Exporter' terminated with reason: {badkey,status,#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>}} in 'Elixir.Imagewatermark':handle_events/3 line 17
2019-05-22 08:20:41.100 [error] <0.300.0> CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: {badkey,status,#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>}} in 'Elixir.Imagewatermark':handle_events/3 line 17 in gen_server:handle_common_reply/8 line 751
2019-05-22 08:20:41.101 [error] <0.229.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.300.0> exit with reason {badkey,status,#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>}} in 'Elixir.Imagewatermark':handle_events/3 line 17 in context child_terminated
2019-05-22 08:24:13.034 [error] <0.308.0> gen_server 'Elixir.Imagewatermark' terminated with reason: bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]}
2019-05-22 08:24:13.038 [error] <0.308.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours exited with reason: bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-22 08:24:13.038 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.308.0> exit with reason bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]} in context child_terminated
2019-05-22 08:24:13.038 [error] <0.309.0> gen_server 'Elixir.Exporter' terminated with reason: bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]}
2019-05-22 08:24:13.039 [error] <0.309.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-22 08:24:13.039 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.309.0> exit with reason bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]} in context child_terminated
2019-05-22 08:25:48.013 [error] <0.307.0> gen_server 'Elixir.Imagewatermark' terminated with reason: bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]}
2019-05-22 08:25:48.017 [error] <0.307.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Imagewatermark' with 0 neighbours exited with reason: bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-22 08:25:48.017 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Imagewatermark' started with 'Elixir.Imagewatermark':start_link([]) at <0.307.0> exit with reason bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]} in context child_terminated
2019-05-22 08:25:48.017 [error] <0.308.0> gen_server 'Elixir.Exporter' terminated with reason: bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]}
2019-05-22 08:25:48.018 [error] <0.308.0>@gen_server:handle_common_reply:751 CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours exited with reason: bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]} in gen_server:handle_common_reply/8 line 751
2019-05-22 08:25:48.018 [error] <0.238.0> Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.308.0> exit with reason bad return value: {reply,ok,[#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}],[]} in context child_terminated
2019-05-22 08:26:31.179 [error] <0.300.0>@Elixir.Exporter:handle_events:14 gen_server 'Elixir.Exporter' terminated with reason: no function clause matching 'Elixir.Exporter':handle_events([#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}], {<0.299.0>,#Ref<0.813555365.2857893894.152012>}, 0) line 14
2019-05-22 08:26:31.186 [error] <0.300.0>@Elixir.Exporter:handle_events:14 CRASH REPORT Process 'Elixir.Exporter' with 0 neighbours crashed with reason: no function clause matching 'Elixir.Exporter':handle_events([#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}], {<0.299.0>,#Ref<0.813555365.2857893894.152012>}, 0) line 14
2019-05-22 08:26:31.186 [error] <0.229.0>@Elixir.Exporter:handle_events:14 Supervisor 'Elixir.BroadwayTest.Supervisor' had child 'Elixir.Exporter' started with 'Elixir.Exporter':start_link([]) at <0.300.0> exit with reason no function clause matching 'Elixir.Exporter':handle_events([#{customer_id => <<"FE51EF">>,file_name => <<"warthog.jpg">>,image_type => <<"jpg">>,status => ok}], {<0.299.0>,#Ref<0.813555365.2857893894.152012>}, 0) line 14 in context child_terminated
